# influnced from https://github.com/pennersr/django-allauth

sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
env:
  matrix:
   - DJANGO="Django<1.5"
   - DJANGO="Django<1.9"
   - DJANGO="Django<1.10"
cache:
  directories:
    - $HOME/.cache/pip
# command to install dependencies
install:
 # pip >=8 dropped Python 3.2 support
 - pip install "pip<8.0.0" wheel
 - pip install "$DJANGO" "coverage==3.7.1" coveralls "mock>=1.0.1"
 - pip install .
 - pip install flake8
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="Django<1.8"
    # Django 1.9+ no longer supports python 3.2/3.3
    - python: "3.2"
      env: DJANGO="Django<1.10"
    - python: "3.3"
      env: DJANGO="Django<1.10"
branches:
 only:
  - master
script:
    # - flake8 --exclude=migrations,south_migrations pastebin
  - coverage run manage.py test pastebin
after_success:
  - coverage report
  - coveralls
